name: CI
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'release-*'
defaults:
  run:
    shell: bash
jobs:
  test_gh_multiline_strings:
    name: Test GH Actions with multiline strings
    runs-on: ubuntu-latest
    steps:
      - name: Normalize TAGS
        shell: bash
        id: normalize_tags
        env:
          TEST: |
            this is the first line
            Line 01
            Line 03
            Line 02
            this is the last line
        run: |
          echo env.TEST
          tags=$(echo '${{ env.TEST }}' | tr '[:upper:]' '[:lower:]')"
          tags="${tags//'%'/'%25'}"
          tags="${tags//$'\n'/'%0A'}"
          tags="${tags//$'\r'/'%0D'}"

          echo "::set-output name=tags::$tags"

      - name: After
        run: echo Tags='${{ steps.normalize_tags.outputs.tags }}'

  test_keptn_install:
    name: Test Keptn install
    runs-on: ubuntu-latest
    steps:
      - name: Install and start K3s
        run: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

      - name: Install Keptn
        id: install_keptn
        uses: keptn-sandbox/action-install-keptn@main
        with:
          KEPTN_VERSION: "0.13.1"
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml

      - name: Test connection to keptn
        run: |
          curl -X GET "${{ steps.install_keptn.outputs.KEPTN_ENDPOINT }}/v1/metadata" -H  "accept: application/json" -H  "x-token: ${{ steps.install_keptn.outputs.KEPTN_API_TOKEN }}"

      - name: Install Helm 
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Checkout keptn-contrib/job-executor-service
        uses: actions/checkout@v2.4.0
        with:
          repository: keptn-contrib/job-executor-service
          path: job-executor-service
        
      - name: Build helm chart
        shell: bash
        working-directory: job-executor-service
        run: gh-actions-scripts/build_helm_chart.sh 0.1.7 0.1.7 job-executor-service

      - name: Install helm chart
        shell: bash
        working-directory: job-executor-service
        run: helm upgrade --install -n keptn job-executor-service installer/job-executor-service-0.1.7.tgz

      - name: Remove helm chart
        shell: bash
        run: helm uninstall -n keptn job-executor-service

      - name: Uninstall Keptn
        uses: keptn-sandbox/action-install-keptn@main
        with:
          UNINSTALL: true
          KEPTN_VERSION: "0.13.1"
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
