name: CI
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'release-*'
defaults:
  run:
    shell: bash
jobs:
  prepare_ci_run:
    name: Prepare CI Run
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Install and start K3s
        run: curl -sfL https://get.k3s.io | sh -

      - name: Install Keptn
        id: install_keptn
        uses: keptn-sandbox/action-install-keptn/.github/actions/install@v1
        with:
          KEPTN_VERSION: "0.13.1"

      - name: Connect to keptn
        run: echo "connect to ${{ steps.install_keptn.outputs.KEPTN_ENDPOINT }} - ${{ steps.install_keptn.outputs.KEPTN_API_TOKEN }}"
