name: CI
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'release-*'
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'release-*'
defaults:
  run:
    shell: bash
jobs:
  test_keptn_install:
    name: Test Keptn install
    runs-on: ubuntu-latest
    steps:
      - name: Install and start K3s
        run: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

      - name: Install Keptn
        id: install_keptn
        uses: keptn-sandbox/action-install-keptn@main
        with:
          KEPTN_VERSION: "0.13.1"
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml

      - name: Connect to keptn
        run: echo "connect to ${{ steps.install_keptn.outputs.KEPTN_ENDPOINT }} - ${{ steps.install_keptn.outputs.KEPTN_API_TOKEN }}"

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Checkout keptn-contrib/job-executor-service
        uses: actions/checkout@v2.4.0
        with:
          repository: keptn-contrib/job-executor-service
          path: job-executor-service

      - name: Build keptn-contrib/job-executor-service
        working-directory: ./job-executor-service
        run: skaffold build

      - name: Run keptn-contrib/job-executor-service
        working-directory: ./job-executor-service
        run: skaffold deploy
    
      - name: Uninstall Keptn
        uses: keptn-sandbox/action-install-keptn@main
        with:
          UNINSTALL: true
          KEPTN_VERSION: "0.13.1"
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
